name: build-test-decision-tree

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: install compiler
      run:   |
         sudo apt update && sudo apt install g++
    - name: setup CMake
      run: mkdir build &&  /usr/local/bin/cmake -S . -B ./build/ -D CMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_VERBOSE_MAKEFILE=ON #/usr/local/bin/x86_64-apple-darwin19-gcc-10.2.0
    - name: run tests
      run: cd build && make && cd test && ./DecisionTests